# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d9ab15d0c8bff8fb2b8759fb404317e58c83db277552a3c04c8c2f009c46cc1c61be9e2990094a5c37a1706ae5819c33e4ea960bb093e97f0035984399ac024a

test:
  secret_key_base: 07c34521c0f5c922168b06d6ae718834788132cfbfcfa7ea7e118baca80c3c90b313687b9e9c6c5b8a19618bb2e727d8dd535948948709544895f697f66b3ba4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
